services:
  database:
    image: postgres:alpine3.20
    restart: always
    environment:
      POSTGRES_USER: gloria
      POSTGRES_PASSWORD: adanna123
      POSTGRES_DB: liberty
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
        
volumes:
  postgres:
